title: Блог о сумках
description: Советы по выбору сумок и модные тренды
avito_url: "ССЫЛКА_НА_ТВОЁ_ОБЪЯВЛЕНИЕ_НА_АВИТО"

url: "https://rusoxy.ru"
baseurl: ""

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
